Add 'make markdownlint'

diff --git a/docs/Makefile b/docs/Makefile
--- a/docs/Makefile
+++ b/docs/Makefile
@@ -1,3 +1,21 @@
+SHELL=bash
+.ONESHELL:
+
+TMPDIR:=$(shell mktemp -d)
+
+## Colored strings?
+ifdef TERM
+	TPUT:=true
+	OK  :=$(shell tput setaf 2; printf "%s" " OK "; tput sgr0)
+	FAIL:=$(shell tput setaf 1; printf "%s" "FAIL"; tput sgr0)
+	YAMLLINT_OPTS:=-f colored
+else
+	TPUT:=false
+	OK  :=$(shell printf "%s" " OK ")
+	FAIL:=$(shell printf "%s" "FAIL")
+	YAMLLINT_OPTS:=
+endif
+
 # Examples:
 # export JEKYLL_HOST=selfhost; make serve 
 # JEKYLL_HOST=selfhost make serve 
@@ -67,5 +85,39 @@ deploy:
 
 yaml-check:
 	@Rscript -e 'paths <- dir(path = c(".", "_data"), pattern = "*[.]yml$$", full.names = TRUE, recursive = TRUE); yaml <- lapply(paths, FUN = yaml::read_yaml)'
+
+markdownlint:
+	@stdout=$(TMPDIR)/stdout
+
+	ok_count=0
+	error_count=0
+	config=.markdownlint.json
+
+	echo "*** markdownlint:"
+	if [[ ! -f "$$config" ]]; then
+	   echo "File not found: $$config (PWD=$$PWD)"
+	   ls -la
+	   exit 1
+	fi
+
+	files=$$(find . -type f -name "*.md" -not -path "./_site/*")
+	for file in $$files; do
+	   $(TPUT) && printf "[    ] checking %s" "$$file"
+	   if markdownlint --config "$$config" "$$file" 2>> "$$stdout" ; then
+	     ok_count=$$((ok_count+1))
+	     $(TPUT) && printf "\r"
+	     printf "[$(OK)] checking %s\\n" "$$file"
+	   else
+	     error_count=$$((error_count+1))
+	     $(TPUT) && printf "\r"
+	     printf "[$(FAIL)] checking %s\\n" "$$file"
+	   fi
+	done
+
+	echo "RESULT: $$ok_count OK, $$error_count ERROR"
+	if (( error_count > 0 )); then
+	  cat "$$stdout"
+	  exit 1
+	fi
 
 FORCE:
