Add 'make markdown-link-check'

diff --git a/docs/Makefile b/docs/Makefile
--- a/docs/Makefile
+++ b/docs/Makefile
@@ -93,7 +93,7 @@ markdownlint:
 	error_count=0
 	config=.markdownlint.json
 
-	echo "*** markdownlint:"
+	echo "*** $@:"
 	if [[ ! -f "$$config" ]]; then
 	   echo "File not found: $$config (PWD=$$PWD)"
 	   ls -la
@@ -117,6 +117,41 @@ markdownlint:
 	echo "RESULT: $$ok_count OK, $$error_count ERROR"
 	if (( error_count > 0 )); then
 	  cat "$$stdout"
+	  exit 1
+	fi
+
+markdown-link-check:
+	@stdout=$(TMPDIR)/stdout
+
+	ok_count=0
+	error_count=0
+	config=.markdown-link-check.json
+
+	echo "*** $@:"
+	if [[ ! -f "$$config" ]]; then
+	   echo "File not found: $$config (PWD=$$PWD)"
+	   ls -la
+	   exit 1
+	fi
+
+	files=$$(find . -type f -name "*.md" -not -path "./_site/*")
+	for file in $$files; do
+	   $(TPUT) && printf "[    ] checking %s" "$$file"
+	   if markdown-link-check --quiet --config "$$config" "$$file" &>> "$$stdout" ; then
+	     ok_count=$$((ok_count+1))
+	     $(TPUT) && printf "\r"
+	     printf "[$(OK)] checking %s\\n" "$$file"
+	   else
+	     error_count=$$((error_count+1))
+	     $(TPUT) && printf "\r"
+	     printf "[$(FAIL)] checking %s\\n" "$$file"
+	   fi
+	done
+
+	echo "RESULT: $$ok_count OK, $$error_count ERROR"
+	if (( error_count > 0 )); then
+	  grep -B 1 -E "(^ERROR:|^\[(✖|x)\]|Status: [0-9]+$$)" "$$stdout"
+	  echo "$$stdout"
 	  exit 1
 	fi
 
